### ISSUE TITLE
Logger vs print() in library. [PR]

### ISSUE THREAD

**Issue by zrthstr** [modbender/tracker-scraper#1]
Hello @modbender, thank you for providing this fantastic library.

I've noticed that the library uses `print()` statements, which for me at least is impractical when using your library. For instance, [here](https://github.com/modbender/tracker-scraper/blob/39dc0b07297ac4d156691c22e0273ea211fb4235/tracker_scraper/scraper.py#L41).

May I suggest a modification to this? I would like to propose a pull request that incorporates minimalistic use of the `logging` module. Would you consider merging such a PR?

If you have a specific approach in mind for addressing this, I'd follow your guidelines. Otherwise, i'll just keep it simple.

Kind regards

**Comment by modbender** [comment]
Oh I have no problem with using logging, I just didn't see the significance since there's only 2 print statements. 

If you know how to then sure go, ahead and open a PR. I'll merge it after checking.

**Comment by modbender** [comment]
I also forgot to add requirements.txt

Only 2 packages are required

'bencode.py',
'requests',

**Comment by zrthstr** [comment]
does this PR look good to you?

>  I just didn't see the significance since there's only 2 print statements.

fair. I guess it is more significant for me as i call your lib hundreds of times...
